format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
condense_wildcard_suffixes = true
match_block_trailing_comma = true
normalize_doc_attributes = true
use_field_init_shorthand = true
overflow_delimited_expr = true
imports_granularity = "Crate"
spaces_around_ranges = true
hex_literal_case = "Upper"
normalize_comments = true
unstable_features = true
use_try_shorthand = true
report_fixme = "Always"
report_todo = "Always"
newline_style = "Unix"
fn_single_line = true
wrap_comments = true
hard_tabs = false
tab_spaces = 4
