contact_links:
  - name: Discussions
    url: https://github.com/gorilla-devs/ferium/discussions
    about: |
      If you are not reporting a bug or requesting a feature,
      e.g. you want to get help on how to use ferium,
      use GitHub Discussions instead of creating an issue.
